server:
  ssl:
    key-store-password: dinh1012
    key-password: dinh1012

spring:
  mail:
    username: "dinhhoang121999@gmail.com"
    password: "f b p s b s w v t w a n s c g p"

  datasource:
    username: root
    password: dinh1012

paypal:
  client-id: "AVyeLvSbaACMA-l1jkzaROgl9OD8oJJ40k1UrxEgk_1lG7qB36JYxbAnGmfuzKs-HGkF8DqbTkNTwe_D"
  client-secret: "EHLA-xCX8ngGGgMY7aU19u_ulsxket4WDwtIQ76KicoIhpasiz7zboFNjePG-pSAYg0KiusdmAjlN-8s"

zalo-pay:
  app-id: 553
  key1: "9phuAOYhan4urywHTh0ndEXiV3pKHr5Q"
  key2: "Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3"

jwt:
  signerKey: "rFpGwv/uscX+l9y5QCe6X5H`3Y825wsLAAuXHT2WgsBiibbVkUj/hrr9GFT+xoEDE"