application:
  name: hotel-system-management

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: dinh1012
    key-store-type: JKS
    key-alias: myssl
    key-password: dinh1012

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "dinhhoang121999@gmail.com"
    password: "f b p s b s w v t w a n s c g p"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_database_management
    username: root
    password: dinh1012
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

paypal:
  mode: sandbox
  client-id: "AVyeLvSbaACMA-l1jkzaROgl9OD8oJJ40k1UrxEgk_1lG7qB36JYxbAnGmfuzKs-HGkF8DqbTkNTwe_D"
  client-secret: "EHLA-xCX8ngGGgMY7aU19u_ulsxket4WDwtIQ76KicoIhpasiz7zboFNjePG-pSAYg0KiusdmAjlN-8s"
  cancel-url: "https://localhost:8443/payment-cancel.html"
  success-url: "https://localhost:8443/payment-success.html"
  error-url: "https://localhost:8443/payment-error.html"

zalo-pay:
  app-id: 553
  key1: "9phuAOYhan4urywHTh0ndEXiV3pKHr5Q"
  key2: "Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3"
  create-order-url: "https://sb-openapi.zalopay.vn/v2/create"
  order-status-url: "https://sb-openapi.zalopay.vn/v2/query"
  redirect-url: "https://localhost:8443/payment-success.html"
  callback-url: https://1da6-118-70-128-190.ngrok-free.app/zalopay/callback

jwt:
  signerKey: "rFpGwv/uscX+l9y5QCe6X5H`3Y825wsLAAuXHT2WgsBiibbVkUj/hrr9GFT+xoEDE"
  valid-duration: 1 #in hour
  refreshable-duration: 7 #in days












































































