application:
  name: hotel-system-management

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: dinh1012
    key-store-type: JKS
    key-alias: myssl
    key-password: dinh1012

spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_database_management
    username: root
    password: dinh1012
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

paypal:
  client-id: "AVyeLvSbaACMA-l1jkzaROgl9OD8oJJ40k1UrxEgk_1lG7qB36JYxbAnGmfuzKs-HGkF8DqbTkNTwe_D"
  client-secret: "EHLA-xCX8ngGGgMY7aU19u_ulsxket4WDwtIQ76KicoIhpasiz7zboFNjePG-pSAYg0KiusdmAjlN-8s"
  mode: sandbox

zalo-pay:
  app-id: 2554
  key1: "sdngKKJmqEMzvh5QQcdD2A9XBSKUNaYn"
  key2: "Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3"
  create-order-url: "https://sb-openapi.zalopay.vn/v2/create"
  redirect-url: https://35dc-14-232-67-63.ngrok-free.app/payment-success.html
  callback-url: https://35dc-14-232-67-63.ngrok-free.app/zalopay/callback

jwt:
  signerKey: "rFpGwv/uscX+l9y5QCe6X5H`3Y825wsLAAuXHT2WgsBiibbVkUj/hrr9GFT+xoEDE"
  valid-duration: 1 #in hour
  refreshable-duration: 7 #in days

























