application:
  name: hotel-system-management

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password:
    key-store-type: JKS
    key-alias: myssl
    key-password:

spring:
  config:
    import: optional:application-secret.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_database_management
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

paypal:
  mode: sandbox
  client-id:
  client-secret:
  cancel-url: "https://localhost:8443/payment-cancel.html"
  success-url: "https://localhost:8443/payment-success.html"
  error-url: "https://localhost:8443/payment-error.html"

zalo-pay:
  app-id:
  key1:
  key2:
  create-order-url: "https://sb-openapi.zalopay.vn/v2/create"
  order-status-url: "https://sb-openapi.zalopay.vn/v2/query"
  redirect-url: "https://localhost:8443/payment-success.html"
  callback-url: https://d9f5-118-70-120-168.ngrok-free.app/zalopay/callback

jwt:
  signerKey:
  valid-duration: 1 #in hour
  refreshable-duration: 7 #in days

gemini:
  api-key:
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"













































































































































