application:
  name: hotel-system-management

server:
  port: 8080
  servlet:
    context-path: /hotel

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_database_management
    username: root
    password: dinh1012
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
